version: '3.8'
services:
  redis:
    image: redis:alpine
    command:
      - redis-server
    ports:
      - '6379:6379'
    container_name: main_Redis
    volumes:
      - redis-data:/data/
      - redis-conf:/usr/local/etc/redis/redis.conf
volumes:
  redis-data:
  redis-conf:
